version: '3.2'
services:
  web:
    depends_on:
      - db
    volumes:
      - ./docker/local/config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  php:
    build:
      dockerfile: ./docker/local/dockerfiles/dockerfile_php7
    links:
      - db
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    networks:
      - internal