version: '3.2'
services:
  web:
    restart: always
    links:
      - php
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - internal
  php:
    restart: always
    networks:
      - internal
networks:
  internal:


