version: '3.2'
services:
  web:
    image: nginx:stable-alpine
    restart: always
    links:
      - php
    ports:
      - "8000:80"
    depends_on:
      - php
      - db
    volumes:
      - ./docker/prod/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./:/var/www/html:rw
    networks:
      - internal
  php:
    build:
      context: .
      dockerfile: ./docker/local/dockerfiles/dockerfile_php7
    restart: always
    links:
      - db
      - redis
    volumes:
      - ./:/var/www/html:rw
    #    - ./docker/config/php:/usr/local/etc/php  //if need overwrite all php
    networks:
      - internal
networks:
  internal:


